### ISSUE TITLE
Better error messaging when port is already in use.

### ISSUE THREAD

**Issue by JeroenKnoops** [cdreier/slide-serve#5]
Now the program just stops when the port is already in use.

It even gives the wrong message:
```starting on port: 8080 for directory presentation```

We might give a reason why it can't start the server.

**Comment by cdreier** [comment]
fixed with eae4fb9235554aa55bef7689cb9cb0cdc57b1782

**Comment by cdreier** [comment]
just build a v0.5.1 release with both fixes :)
