### ISSUE TITLE
An empty line in code snippets.

### ISSUE THREAD

**Issue by JeroenKnoops** [cdreier/slide-serve#9]
When you insert a snippet of code, it's common to have empty lines in it.

```
@code/js
  export function noSSR (LoadableInitializer, loadableOptions) {
    // Removing webpack and modules means react-loadable won't try preloading
    delete loadableOptions.webpack
    delete loadableOptions.modules

    // This check is neccesary to prevent react-loadable from initializing on the server
    if (!isServerSide) {
      return LoadableInitializer(loadableOptions)
    }

    // This will only be rendered on the server side
    return () => <loadableOptions.loading error={null} isLoading pastDelay={false} timedOut={false} />
  }
```

Now we're adding extra comments.

**Comment by cdreier** [comment]
hmm, i just have the same problem, not sure if i found a good solution.

for now, i removed spaces from the cleanup, the renderer can find the 2 spaces at the beginning. for me it seems like an easy fix.

will push it, perhaps you can test it for your content and give short feedback :)

**Comment by JeroenKnoops** [comment]
This was the quick fix I also had in mind. I will test it as soon as I’m home. Thanks!

**Comment by JeroenKnoops** [comment]
You are amazing!

<img width="1270" alt="screenshot 2019-02-20 at 07 17 13" src="https://user-images.githubusercontent.com/10019/53070465-9a255500-34df-11e9-9f2f-106f9f2bed35.png">

Thanks. Now this will be used by more of my colleagues!

**Comment by cdreier** [comment]
glad to hear that :)
